/**
 * Rebuild every served image from the originals.
 *
 *   node scripts/optimize-images.cjs          # rebuild public/ from assets-src/
 *   node scripts/optimize-images.cjs --dry    # report only
 *
 * Why this exists: the doors were shipping 1200x1760 JPEGs to paint a 259x380
 * tile, and the gallery thumbnail strip was downloading full 1920x1080 frames
 * to paint 90x58 chips — 2.6 MB of images on the hall alone.
 *
 * Layout:
 *   assets-src/**            the untouched originals — the archive, never served
 *   public/projects/**       generated WebP only, sized to what is painted
 *
 * Originals are MOVED here on first run, so nothing is lost and nothing is
 * shipped twice. Re-run after adding a project (drop its originals in
 * assets-src/projects/<slug>/ first).
 */
const fs = require("node:fs");
const path = require("node:path");
const sharp = require("sharp");

const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "assets-src");
const PUB = path.join(ROOT, "public");
const DRY = process.argv.includes("--dry");

// Painted sizes measured in the browser at 1280x720, doubled for retina.
//   door cover   259x380  -> 560 wide
//   gallery main 828x466  -> 1600 wide (also covers a 1440px viewport)
//   thumb chip    90x58   -> 240 wide
// Gallery frames sit at q68: they are grainy AI-generated renders, and grain is
// exactly what a lossy codec spends its bitrate on. At 1600px the difference is
// invisible while the heaviest frame drops from 382 KB to well under a third.
const RULES = [
  // The portrait is the one image on the first screen, and it is painted at
  // wildly different sizes: 324 CSS px on a desktop, 294 on a phone — times a
  // device pixel ratio of anywhere from 1 to 3. One 720px file served all of
  // them, which meant a 1x laptop downloaded four times the pixels it drew.
  // These extra widths let the browser choose (see `srcset` in Hero.jsx);
  // 720 stays the top of the ladder for 3x phones and 2x desktops.
  { test: /(^|\/)ahmed\.\w+$/i, width: 720, quality: 82, thumb: false, extra: [360, 540] },
  { test: /(^|\/)cover\.\w+$/i, width: 560, quality: 76, thumb: false },
  { test: /.*/, width: 1600, quality: 68, thumb: true },
];
const THUMB = { width: 240, quality: 70 };
// The phone variant. A gallery frame paints at 253x142 on a 390px screen, but
// the browser was handed the full 1600px file and had to decode 1.44 megapixels
// on a phone CPU — measured as a 185ms main-thread block every time a project
// door opened. Projects.jsx serves this one to small screens via <picture>,
// which (unlike srcset/sizes) is not overridden by a 3x device pixel ratio.
const SMALL = { width: 900, quality: 68 };

// og.jpg must stay a JPEG: WhatsApp/Facebook/LinkedIn scrapers still reject
// WebP share cards. The favicon is left alone too.
//
// The three PWA icons are here because migrate() below sweeps every raster out
// of public/ on sight, and these are not source photos — they are generated by
// scripts/make-icons.cjs and named as PNG by app/manifest.js. Without this line
// a run of this script moves them into assets-src/, replaces them with WebP,
// and the manifest quietly points at three 404s: the install prompt loses its
// icon and nothing in the build warns. Measured the day two projects were
// added; the icons had been generated after the previous run, so the bug had
// never had a chance to fire before.
const KEEP_AS_IS = new Set([
  "og.jpg",
  "favicon.ico",
  "icon-192.png",
  "icon-512.png",
  "icon-maskable.png",
]);

const isRaster = (f) => /\.(jpe?g|png)$/i.test(f);
const walk = (d) =>
  fs.existsSync(d)
    ? fs
        .readdirSync(d, { withFileTypes: true })
        .flatMap((e) => (e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)]))
    : [];

/** First run: move the originals out of public/ into assets-src/. */
function migrate() {
  const originals = walk(PUB).filter((f) => isRaster(f) && !KEEP_AS_IS.has(path.basename(f)));
  if (!originals.length) return 0;
  for (const f of originals) {
    const dest = path.join(SRC, path.relative(PUB, f));
    if (DRY) continue;
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.renameSync(f, dest);
  }
  return originals.length;
}

const kb = (n) => (n / 1024).toFixed(0);

(async () => {
  const moved = migrate();
  if (moved) console.log(`moved ${moved} originals into assets-src/\n`);

  const sources = walk(SRC).filter(isRaster);
  if (!sources.length) {
    console.error("no originals found in assets-src/ — nothing to do.");
    process.exitCode = 1;
    return;
  }

  let before = 0;
  let after = 0;
  const rows = [];

  for (const src of sources) {
    const rel = path.relative(SRC, src).split(path.sep).join("/");
    const rule = RULES.find((r) => r.test.test(rel));
    const meta = await sharp(src).metadata();
    const srcBytes = fs.statSync(src).size;
    before += srcBytes;

    const outputs = [
      { suffix: "", width: rule.width, quality: rule.quality },
      ...(rule.thumb ? [{ suffix: "-sm", ...SMALL }, { suffix: "-thumb", ...THUMB }] : []),
      // Named by width, because that is what the `srcset` descriptor has to
      // say — `ahmed-360.webp 360w`. A suffix like `-sm` would force whoever
      // writes the srcset to remember which number it stood for.
      ...(rule.extra || []).map((w) => ({ suffix: `-${w}`, width: w, quality: rule.quality })),
    ];

    for (const o of outputs) {
      const outRel = rel.replace(/\.\w+$/, `${o.suffix}.webp`);
      const out = path.join(PUB, outRel);
      // Never upscale: a source smaller than the target keeps its own size.
      const w = Math.min(o.width, meta.width);
      if (!DRY) {
        fs.mkdirSync(path.dirname(out), { recursive: true });
        await sharp(src)
          .resize({ width: w, withoutEnlargement: true })
          .webp({ quality: o.quality, effort: 6 })
          .toFile(out);
      }
      const outBytes = DRY ? 0 : fs.statSync(out).size;
      after += outBytes;
      rows.push(
        `${kb(srcBytes).padStart(5)} KB ${`${meta.width}x${meta.height}`.padEnd(10)}` +
          ` ->${kb(outBytes).padStart(5)} KB ${`${w}w`.padEnd(6)} ${outRel}`
      );
    }
  }

  console.log(rows.sort().join("\n"));
  console.log("\n" + "-".repeat(60));
  console.log(
    `${sources.length} originals (${(before / 1024 / 1024).toFixed(2)} MB)` +
      ` -> ${rows.length} WebP (${(after / 1024 / 1024).toFixed(2)} MB)` +
      `   saved ${(((before - after) / before) * 100).toFixed(0)}%`
  );
  if (DRY) console.log("(dry run — nothing written)");
})();
